@API = http://localhost:3000

//GET ALL MESA DE EXAMENES (POR ALUMNO)
GET {{API}}/mesa_examenes/39819973

//GET ALL MESA DE EXAMENES INSCRIPTAS (POR ALUMNO)
###
GET {{API}}/mesa_examenes_inscriptas/39819973

//INSCRIPCION MESA DE EXAMEN
###
POST {{API}}/inscripcion_mesa
Content-Type: application/json

{
    "alumnoID": "39819973",
    "mesaID": "1"
}

//GET ALL CURSOS
###
GET {{API}}/cursos

//GET ALUMNOS X CURSO
###
GET {{API}}/alu_cursos/2

//GET ALL MATERIAS
###
GET {{API}}/materias

//GET CLASES X MATERIA
###
GET {{API}}/clase_materia/1

//GET REGIMEN X MATERIA
###
GET {{API}}/regimen_materia/1


//SANCIONAR ALUMNO
###
POST {{API}}/sancion
Content-Type: application/json

{
    "alumnoID": "39819973",
    "docenteID": "42555120",
    "tipoSancion": "Leve",
    "descripcion": "duerme en clases",
    "fecha": "2021-11-24"
}

//GUARDAR CALIFICACIONES
###
POST {{API}}/guardar_nota
Content-Type: application/json

{
    "alumnoID": "39819973",
    "docenteID": "42555120",
    "materiaID": "1",
    "regimen": "Anual",
    "etapa": "1",
    "nota": "10",
    "descripcion": "Mesa de examenes Diciembre"
}

//TOMAR ASISTENCIA
###
POST {{API}}/guardar_asistencia
Content-Type: application/json

{
    "alumnoID": "39819973",
    "claseID": "2",
    "estado": "Presente"
}
//OBTENER ASISTENCIAS
###
GET {{API}}/asistencias/39819975/2/2022-01-31


###
PUT {{API}}/edit_asistencia
Content-Type: application/json

{
    "estado": "Presente",
    "id": "21"
}

###
GET {{API}}/calificaciones/Examen de derivadas

###
GET {{API}}/descripcion_notas/39819975/1