@API = http://localhost:3000



//GET MESA EXAMENES POR ALUMNO
GET {{API}}/mesa_examenes/39819973

//GET MESA EXAMENES INSCRIPTAS POR ALUMNO
###
GET {{API}}/mesa_examenes_inscriptas/39819973

//GET ID ALUMNO POR NOMBRE
###
GET {{API}}/id_alumno/ponja

//GET ALL CURSOS
###
GET {{API}}/cursos

//GET ALUMNOS X CURSO
###
GET {{API}}/alu_cursos/4

//SANCIONAR ALUMNO
###
POST {{API}}/sancion
Content-Type: application/json

{
    "alumnoID": "2",
    "docenteID": "4",
    "tipoSancion": "Leve",
    "descripcion": "duerme en clases",
    "fecha": "2021-10-31"
}

//INSCRIBIRSE EN MESA DE EXAMEN
###
POST {{API}}/inscripcion_mesa
Content-Type: application/json

{
    "alumnoID": "2",
    "mesaID": "1"
}

//GET ALL MATERIAS
###
GET {{API}}/materias

//GET CLASES X MATERIA
###
GET {{API}}/clase_materia/1

//GET REGIMEN X MATERIA
###
GET {{API}}/regimen_materia/1